name: instagram_clone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+2
  firebase_analytics: ^5.0.9
  firebase_auth: ^0.15.3+1
  firebase_storage: ^3.1.1
  cloud_firestore: ^0.13.0+1
  provider: ^3.0.0+1
  image_picker: ^0.6.1+4
  image_cropper: ^1.1.2
  flutter_image_compress: ^0.6.5+1
  cached_network_image: ^2.0.0
  path_provider: ^1.5.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/boy.png
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
